### ISSUE TITLE
Is the "shine" LED light strip programmable?

### ISSUE THREAD

**Issue by leoj3n** [algernon/ergodox-layout#134]
I'm not sure you have the "Shine" EZ model with the multi-color LED strips on the back of the left and right keyboard, but perhaps you can still answer a question I have since you're very familiar with firmware and the like.

Do you think it is possible to programmatically control the backlight LED colors? In the [configurator](http://configure.ergodox-ez.com/keyboard_layouts/new) it is possible to bind keys to change color/brightness/animation of the backlight LED strips, but I'm only interested in the ability to control them passively depending on current keyboard layer, or perhaps how long the user has been AFK, or the time of day.

Is it possible to control this part of the keyboard either by forking the firmware or better yet in user settings? If so, to what extent? I'm guessing there is limited space for code like this on the board itself? Can code running on the host machine interact with the board in real time?

A few questions, sorry if they're kind of intertwined; haven't been able to find much info. Thanks!

**Comment by algernon** [comment]
Nope, both my EZs are of the older model, not the Shine one. Nevertheless, I can answer some of your questions!

> Do you think it is possible to programmatically control the backlight LED colors?

Yeah, they are! Look in [quantum/rgblight.h](https://github.com/qmk/qmk_firmware/blob/master/quantum/rgblight.h) for functions that can be used to program the strip.

> ...the ability to control them passively depending on current keyboard layer, or perhaps how long the user has been AFK, or the time of day.

It is possible to change the colors of the strip, with - as far as I see - `rgblight_setrgb()`, so you can look at the active layer from the `matrix_scan_user()` function, and update the lights based on the layer. You can also use a timer there, that gets reset every time a key is released, so if it goes too high, the user is AFK, and you can turn off the lights. Mind you, it counts in milliseconds, and there's a finite number of those that you can store (16bits of time, as far as I remember), so you can't have super-long timeouts.

The keyboard does not have access to the time of the day, though, the clock it has is only used for relative timing things. So sadly, you can't set the lights based on the time of day. Not without talking to the keyboard.

> Can code running on the host machine interact with the board in real time?

Not currently. As it happens, I'm working with HaTaa on a protocol and firmware enhancements that would allow exactly this. It is nowhere near ready yet, and the QMK bits aren't even there, but [hid-io](https://github.com/hid-io/hid-io) is where things are happening.

For the Keyboardio Model 01, I already created a plugin that implements bidirectional communication between keyboard and host, so this kind of thing is possible. QMK does not have this feature yet, though.

> I'm guessing there is limited space for code like this on the board itself?

The LED stuff doesn't use much space on the board, I suppose. Changing the color depending on layer, or if the user is AFK should be a few dozen bytes extra. And most keymaps have plenty of space left... mine is around 28k, which is pushing the limits (89% full), but my keymap is a pretty darn complex one.

**Comment by leoj3n** [comment]
Excellent news! Thank you for the detailed and helpful response. Due to them being programmable, I'm definitely going to add on the light strips to my order (otherwise I wouldn't bother). The link to the header file was very helpful, and those provided functions should allow me to do most of what I might desire. The two-way communication would potentially allow for some very interesting interactions, and is certainly something I'd love to see developed!

**Comment by algernon** [comment]
Glad I could help!
