### ISSUE TITLE
Tool to generate the ascii art in the keymap?

### ISSUE THREAD

**Issue by cmaughan** [algernon/ergodox-layout#139]
Hi,
I'm just getting started; I wanted to build my own layout firmware, but I've noticed that you and others have a layout keymap.c file with ascii art and key assignments.  The ergodox configurator just outputs arrays of key identifiers for me in the .c file - I don't get the handy layout ascii art in the c file.  Just wondering how you do that?  Are you manually editing it?  Thanks!

**Comment by algernon** [comment]
Yep, I'm manually editing. I really should find (or write) a tool to do it for me, but so far, I've been way too lazy to do that.
