### ISSUE TITLE
sorry to disturb

### ISSUE THREAD

**Issue by andno037** [algernon/ergodox-layout#55]
sorry to disturb with maybe a stupid question but I have a ergodox_ez and saw your layout and wanted to try it out. But now it is so that when I have programed the keyboard with what is now on your master branch I can not write anything. I can however see the lights change colors as they should when I have pressed Shift, etc. Could you upload a compiled hex file if it's something I'm doing wrong when compiling

**Comment by algernon** [comment]
[Here](https://asylum.madhouse-project.org/algernon/typing/ergodox-layout/ergodox_ez_algernon-master.hex) is the latest HEX, hopefully it helps.

Did you try both halves of the EZ? Does my layout included with QMK work?

I did some changes over the weekend, which I have not tried myself either (keyboard is at work), so I may have broken something, though I doubt it.

**Comment by andno037** [comment]
hi again no that file did not work for me.
And the version that is on qmk do not work.
I have look back in git history and fond the first commit that works for me is 489d779fb32dad6542bbbde337e036d67c32007
but I just made a fast script compiling one file for every commit in history and then I tested some of them. So there can be one more resent that works put I do not think so. ps I compilde from ergodox_ez foldern.

**Comment by algernon** [comment]
Hrm. The one on QMK works for me... Do you have issues with other keymaps, or only this one?

**Comment by andno037** [comment]
yes the ones I have tried work in qmk (droak colemak plover german)

**Comment by andno037** [comment]
dvorak *

**Comment by algernon** [comment]
Interesting... but I have a suspicion! If you remove the `FORCE_NKRO` line from `config.h`, does that fix the issue?

By the way, which operating system are you using?

**Comment by andno037** [comment]
hi again, Yes you were right if I remove the force_nkro it works. And yes I'am sitting on a windows machein(but I thingk you allredy know that). And it works on my linux to with out removing the line. Thanks for the help, I muste say you have done a really nice job with your keyborad layout and can't wait to test it out more.

**Comment by algernon** [comment]
Great, thanks for testing, and sticking around until this was figured out, much appreciated!

I'll add an option to the keyboard to easily disable `FORCE_NKRO`, like `make KEYMAP=algernon NO_FORCE_NKRO=1` or similar - will document it in the README.
