### ISSUE TITLE
one hand mode

### ISSUE THREAD

**Issue by pvinis** [algernon/ergodox-layout#71]
how does it work? you tap on the keys to get the left hand variation, and how do you get the right hand variation of each key?
i couldnt figure it out from your config..

**Comment by algernon** [comment]
You tap the `OTHER` key to switch sides. So if you want to type, say, *hello world*, the keypresses are as follows:

`OTHER`, `h`, `OTHER`, `e`, `OTHER`, `l`, `l`, `OTHER`, `o`, `SPACE`, `OTHER`, `w`, `OTHER`, `r`, `l`, `d`.

Not the most convenient, but the one-handed layout is something I use very, very rarely, so it has seen little tuning so far.

**Comment by pvinis** [comment]
ah ok. cool hack :). thanks for explaining.

On Fri, Jul 1, 2016 at 15:19, Gergely Nagy <notifications@github.com> wrote:
You tap the OTHER key to switch sides. So if you want to type, say, hello world , the keypresses are as follows:

OTHER , h , OTHER , e , OTHER , l , l , OTHER , o , SPACE , OTHER , w , OTHER , r , l , d .

Not the most convenient, but the one-handed layout is something I use very, very rarely, so it has seen little tuning so far.

**Comment by algernon** [comment]
You're welcome, I'm always happy when someone tries to use my layout :)
